INSERT INTO Currency (name, code) VALUES ('Dolar amerykanski', 'USD')
INSERT INTO Currency (name, code) VALUES ('Dolar australijski', 'AUD')
INSERT INTO Currency (name, code) VALUES ('Dolar kanadyjski', 'CAD')
INSERT INTO Currency (name, code) VALUES ('forint', 'HUF')
INSERT INTO Currency (name, code) VALUES ('Frank szwajcarski', 'CHF')
INSERT INTO Currency (name, code) VALUES ('Funt szterling', 'GBP')
INSERT INTO Currency (name, code) VALUES ('jen', 'JPY')
INSERT INTO Currency (name, code) VALUES ('korona czeska', 'CZK')
INSERT INTO Currency (name, code) VALUES ('korona dunska', 'DKK')
INSERT INTO Currency (name, code) VALUES ('korona norweska', 'NOK')
INSERT INTO Currency (name, code) VALUES ('korona szwedzka', 'SEK')
INSERT INTO Currency (name, code) VALUES ('SDR', 'XDR')